on:
  push:
    tags: ['*']
name: deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
      with:
        depth: 1
    - name: Deploy to PyPI
      uses: abatilo/actions-poetry@v1.1.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0.2
        args: publish --build -u __token__ -p ${{secrets.PYPI_TOKEN}}
