on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
name: tests
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
    - name: Run unit tests
      run: python -mtests -v
