on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
name: tests
jobs:
  tests:
    if: |
      contains(github.event.commits[0].message, '[skip ci]') == false &&
      contains(github.event.commits[0].message, '[ci skip]') == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7, 3.8]
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
      with:
        depth: 1
    - name: Set up Python ${{matrix.python}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python}}
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.3
      with:
        version: 1.0.2
    - name: Install dependencies
      run: |
        pip install django
        poetry install
    - name: Run unit tests
      run: python -m tests -v
